apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jce-cfc-app-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/Call-for-Code-for-Racial-Justice/fix-politics
  - name: revision
    value: lift-to-ocp
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cfc-app-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/Call-for-Code-for-Racial-Justice/fix-politics
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cfc-app-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/cfc-app/cfc-app:latest
