kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: example
  namespace: legit-info
  selfLink: /apis/networking.k8s.io/v1beta1/namespaces/legit-info/ingresses/example
  uid: 1bb3cbe0-0167-4258-8e34-2b2e92a4b835
  resourceVersion: '49915623'
  generation: 3
  creationTimestamp: '2020-10-14T21:54:40Z'
spec:
  rules:
    - host: >-
        embrace-dev-ocp43-vpc-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: cfc-app
              servicePort: 3000
status:
  loadBalancer: {}
